removed old config samples renamed workers and split into different files modified loader to use the new salt-syntax

diff --git a/debian/salt-eventsd/DEBIAN/postinst b/debian/salt-eventsd/DEBIAN/postinst
--- a/debian/salt-eventsd/DEBIAN/postinst
+++ b/debian/salt-eventsd/DEBIAN/postinst
@@ -4,12 +4,27 @@ set -e
 
 case "$1" in
     configure)
-        mv /etc/salt/eventsd.simple /etc/salt/eventsd
+        if [ -f /etc/salt/eventsd.simple ]
+	then
+            mv /etc/salt/eventsd.simple /etc/salt/eventsd
+	fi
 	if ! [ -d /etc/salt/eventsd_workers ]
 	then
 	    mkdir /etc/salt/eventsd_workers
 	fi
-        zcat /usr/share/doc/salt-eventsd/eventsd_workers/MysqlWorker.py.gz > /etc/salt/eventsd_workers/MysqlWorker.py
+        if [ -f /usr/share/doc/salt-eventsd/eventsd_workers/MysqlWorker.py.gz ]
+	then
+            zcat /usr/share/doc/salt-eventsd/eventsd_workers/MysqlWorker.py.gz > /etc/salt/eventsd_workers/MysqlWorker.py
+	fi
 	/usr/sbin/update-python-modules -f
     ;;
 esac
+
+update-rc.d salt-eventsd defaults
+
+if [ $? -eq 0 ]
+then
+    echo "created start-up links"
+else
+    echo "failed to create start-up links, please create them yourself"
+fi
